### ISSUE TITLE
Undefined variable: aws_plugin_version

### ISSUE THREAD

**Issue by webdj-agency** [flowdee/amazon-product-in-a-post-plugin#2]
Error:
Undefined variable: aws_plugin_version in amazon-product-in-a-post-plugin/inc/amazon-product-in-a-post-activation.php (lines 41, 42):
add_option("apipp_version", $aws_plugin_version);
add_option("apipp_dbversion", $aws_plugin_version);

Solution:
add_option("apipp_version", APIAP_PLUGIN_VER);
add_option("apipp_dbversion", APIAP_DBASE_VER);

**Comment by flowdee** [comment]
Can you check if this issue still occurs with the latest v5.1 version? @webdj-agency

**Comment by webdj-agency** [comment]
yes will check soon

**Comment by webdj-agency** [comment]
yeah. it generates the error still. will push the update now
